version: '3.7'

services:

  cli:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      DiscordToken: ${DiscordToken}
      Prefix: "!"
      DbFilename: "db.lite"
      Roles: "Moderator,Administrator"