version: '3.7'

services:

  cli:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      Discord__Token: ${Discord__Token}
      Db__Path: ${Db__Path:-/tmp/lite/disinfo.db}
    volumes:
      - type: bind
        source: ./lite/
        target: /tmp/lite/
      - type: bind
        source: ./sql/
        target: /tmp/sql/
