version: '3.7'

services:

  cli:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      DiscordToken: "NTkwMzk4NjIwMjQ4MDQ3NjI1.XV3CvQ.j9U8KEldnLcTfEFneFrpM5gdzLI"
      Prefix: "!"
      DbFilename: "db.lite"
      Roles: "Moderator,Administrator"