version: '3.7'

services:

  cli:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      Discord__Token: ${DiscordToken}
      Db__Path: "/db/disinfo.db"
    volumes:
      - type: bind
        source: ${DbPath:-./dbs}
        target: /db
